/// $GCH uses 6 decimals: 1 GCH = 1_000_000 base units.
pub const GCH_LAMPORTS: u64 = 1_000_000;
pub const DEFAULT_BASE_YIELD_LAMPORTS: u64 = 100 * GCH_LAMPORTS;
pub const POTION_BURN_LAMPORTS: u64 = 100 * GCH_LAMPORTS;
pub const MAX_BASE_YIELD_LAMPORTS: u64 = 10_000 * GCH_LAMPORTS;
pub const MAX_FEE_BPS: u16 = 100; // 1% hard cap
pub const ARCHITECT_TAX_BPS: u64 = 100; // 1%
pub const BPS_DENOMINATOR: u64 = 10_000;
pub const DEFAULT_SCORE_UPDATE_COOLDOWN_SECONDS: i64 = 0;
pub const DEFAULT_MIN_EPOCH_SCORE: u64 = 1;
pub const DEFAULT_MAX_CONTRIBUTORS_PER_EPOCH: u32 = 500;
pub const DEFAULT_FEE_BURN_BPS: u16 = 4_000; // 40% of fee stream
pub const DEFAULT_FEE_JACKPOT_BPS: u16 = 4_000; // 40% of fee stream
pub const DEFAULT_MAX_STARTERS_PER_MANAGER: u8 = 11;
pub const STAMINA_DRAIN_PER_MATCH: u8 = 30;

/// PDA Seeds
pub const SEED_CONFIG: &[u8] = b"config";
pub const SEED_BUILDER_FUND: &[u8] = b"builder_fund";
pub const SEED_BUILDER_VAULT: &[u8] = b"builder_vault";
pub const SEED_CONTRIBUTOR_SCORE: &[u8] = b"contributor_score";
pub const SEED_BUILDER_EPOCH: &[u8] = b"builder_epoch";
pub const SEED_EPOCH_CONTRIBUTOR: &[u8] = b"epoch_contributor";
pub const SEED_EPOCH_CLAIM: &[u8] = b"epoch_claim";
pub const SEED_STAKE: &[u8] = b"stake";
pub const SEED_STAKE_VAULT: &[u8] = b"stake_vault";
pub const SEED_PLAYER: &[u8] = b"player";
pub const SEED_RENTAL: &[u8] = b"rental";
pub const SEED_WAGER: &[u8] = b"wager";
pub const SEED_WAGER_VAULT: &[u8] = b"wager_vault";
pub const SEED_FIXTURE: &[u8] = b"fixture";
pub const SEED_FIXTURE_VAULT: &[u8] = b"fixture_vault";
pub const SEED_BET: &[u8] = b"bet";
pub const SEED_LIVE_STATE: &[u8] = b"live_state";
pub const SEED_MARKET: &[u8] = b"market";
pub const SEED_MARKET_VAULT: &[u8] = b"market_vault";
pub const SEED_POSITION: &[u8] = b"position";
pub const SEED_MANAGER: &[u8] = b"manager";
pub const SEED_STADIUM: &[u8] = b"stadium";
pub const SEED_MANAGER_DAILY_CLAIM: &[u8] = b"manager_daily_claim";
pub const SEED_PLAYER_MATCH: &[u8] = b"player_match";
pub const SEED_PRESALE: &[u8] = b"presale";
pub const SEED_LOCALNET_VAULT: &[u8] = b"localnet_vault";