#!/usr/bin/env bash
# install-gbrainsync-macos.sh
#
# One-shot installer for macOS: registers a launchd daemon that polls the VPS
# gbrain-sync server every 60 seconds over Tailscale and runs
# `gbrain import ai_context docs/intake` on every diff.
#
# Usage:
#   VPS_TS_IP=100.101.211.44 VPS_LAN_HOSTNAME=goalworld.local bash install-gbrainsync-macos.sh [--uninstall]
#
# Idempotent. Safe to re-run. Safe to run with --uninstall at any time.
#
# Pre-requisites (silently auto-detected; failures are loud):
#   - macOS (Darwin). Print error and exit 1 otherwise.
#   - `tailscale` CLI installed (otherwise print install link, exit 2).
#   - `gbrain` CLI installed and on PATH (otherwise fall back to `~/.bun/bin`).
#   - The repo lives at ~/hermes/workspace/goalworld (or $goalworld_REPO_PATH).
#
# After install:
#   - A launchd plist at ~/Library/LaunchAgents/com.goalworld.gbrainsync.plist
#     runs every 60s.
#   - Logs to ~/.gbrain/sync/client.log
#   - First poll triggers within ≤5s of bootstrap.
#
set -euo pipefail

#--- config --------------------------------------------------------------
VPS_TS_IP="${VPS_TS_IP:-100.101.211.44}"
VPS_SYNC_PORT="${VPS_SYNC_PORT:-8648}"
LABEL="com.goalworld.gbrainsync"
PLIST_PATH="$HOME/Library/LaunchAgents/${LABEL}.plist"
LOG_DIR="$HOME/.gbrain/sync"
LOG_FILE="$LOG_DIR/client.log"
REPO_PATH="${goalworld_REPO_PATH:-$HOME/hermes/workspace/goalworld}"
CLIENT_SCRIPT="$HOME/.gbrain/sync/gbrainsync-client.sh"
SUBDIRS=("ai_context" "docs/intake")

#--- helpers -------------------------------------------------------------
log()  { printf '[gbrainsync-install] %s\n' "$*"; }
warn() { printf '[gbrainsync-install] WARN: %s\n' "$*" >&2; }
err()  { printf '[gbrainsync-install] ERROR: %s\n' "$*" >&2; }
die() { err "$*"; exit "$1"; }

#--- pre-flight (only when installing, not removing) ----------------------
preflight() {
  if [[ "$(uname)" != "Darwin" ]]; then
    err "this installer targets macOS only"
    exit 1
  fi
  if ! command -v tailscale >/dev/null 2>&1; then
    err "tailscale not found on PATH. Install it from https://tailscale.com/download/mac then run \`tailscale up\`, then re-run this script."
    exit 2
  fi
  if ! tailscale status >/dev/null 2>&1; then
    err "tailscale daemon not running. Run \`tailscale up\` first."
    exit 2
  fi
  if ! command -v gbrain >/dev/null 2>&1 && ! [[ -x "$HOME/.bun/bin/gbrain" ]]; then
    err "gbrain CLI missing; on mac: \`curl -fsSL https://bun.sh/install | bash\` then \`bun install -g gbrain\`."
    exit 2
  fi
  if [[ ! -d "$REPO_PATH" ]]; then
    err "goalworld repo not found at $REPO_PATH (set goalworld_REPO_PATH)."
    exit 2
  fi
  command -v rsync >/dev/null 2>&1 || warn "rsync not found — sync will use plain curl polling only"
}

#--- uninstall helper ----------------------------------------------------
uninstall() {
  log "removing launchd job $LABEL"
  launchctl bootout "gui/$(id -u)/${LABEL}" 2>/dev/null || \
    launchctl unload "$PLIST_PATH" 2>/dev/null || true
  rm -f "$PLIST_PATH"
  log "ok. plist gone. log dir kept at: $LOG_DIR"
  log "nuke everything: rm -rf '$LOG_DIR'"
  exit 0
}

#--- main ----------------------------------------------------------------
if [[ "${1:-}" == "--uninstall" ]]; then
  uninstall
fi

preflight

#--- generate the wrapper that the launchd job calls -----------------------
mkdir -p "$LOG_DIR"

cat > "$CLIENT_SCRIPT" <<'PREAMBLE'
#!/usr/bin/env bash
# gbrainsync-client.sh — auto-generated by install-gbrainsync-macos.sh.
# Polls VPS GBrain sync server every 60s, pulls diff + imports gbrain.
set -euo pipefail
export PATH="$HOME/.bun/bin:$HOME/.local/bin:$PATH"
VPS_TS_IP="__VPS_TS_IP__"
VPS_SYNC_PORT="__VPS_SYNC_PORT__"
REPO_PATH="__REPO_PATH__"
SUBDIRS=( __SUBDIRS__ )
STATE_FILE="$HOME/.gbrain/sync/last-sync.ts"
LOG_FILE="$HOME/.gbrain/sync/client.log"
mkdir -p "$(dirname "$STATE_FILE")"
LAST=$(cat "$STATE_FILE" 2>/dev/null || echo 0)
NOW_EPOCH=$(date +%s)
HEALTH_URL="http://${VPS_TS_IP}:${VPS_SYNC_PORT}/health"
SYNC_URL="http://${VPS_TS_IP}:${VPS_SYNC_PORT}/sync/since/${LAST}"
{
  echo "--- tick @ $NOW_EPOCH (since=$LAST) ---"
  if ! curl -fsS --max-time 10 "$HEALTH_URL" >/dev/null; then
    echo "HEALTH_FAIL: VPS $VPS_TS_IP unreachable (tailscale/ACL?)"
    exit 0  # benign — keep the loop alive
  fi
  RESP=$(curl -fsS --max-time 10 "$SYNC_URL" || true)
  if [[ -z "$RESP" ]] || [[ "$RESP" == "[]" ]]; then
    echo "no changes since $LAST"
    echo "$NOW_EPOCH" > "$STATE_FILE"
    exit 0
  fi
  COUNT=$(printf '%s' "$RESP" | python3 -c 'import sys,json;print(len(json.load(sys.stdin)))' 2>/dev/null || echo 0)
  echo "fetched $COUNT change-records — running gbrain import"
  cd "$REPO_PATH"
  if [[ -d .git ]]; then
    git pull --ff-only >/dev/null 2>&1 || echo "git pull skipped (offline/diverged)"
  fi
  gbrain import "${SUBDIRS[@]}" 2>&1 || {
    echo "gbrain import failed (pglite lock?); will retry next tick"
    exit 0
  }
  echo "$NOW_EPOCH" > "$STATE_FILE"
  echo "ok"
} >> "$LOG_FILE" 2>&1
PREAMBLE
chmod +x "$CLIENT_SCRIPT"

#--- materialize placeholders (uv-safe) -----------------------------------
python3 -c "
import pathlib,sys
p = pathlib.Path('$CLIENT_SCRIPT')
s = p.read_text()
s = s.replace('__VPS_TS_IP__',     '$VPS_TS_IP')
s = s.replace('__VPS_SYNC_PORT__', '$VPS_SYNC_PORT')
s = s.replace('__REPO_PATH__',     '$REPO_PATH')
s = s.replace('__SUBDIRS__',       ' '.join('\"{}\"'.format(d) for d in ('${SUBDIRS[@]}')))
p.write_text(s)
"

#--- write the launchd plist ----------------------------------------------
mkdir -p "$(dirname "$PLIST_PATH")"
cat > "$PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LABEL}</string>

  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>-lc</string>
    <string>${CLIENT_SCRIPT}</string>
  </array>

  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>${HOME}/.bun/bin:${HOME}/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
  </dict>

  <key>RunAtLoad</key>
  <true/>

  <key>StartInterval</key>
  <integer>60</integer>

  <key>StandardOutPath</key>
  <string>${LOG_FILE}</string>

  <key>StandardErrorPath</key>
  <string>${LOG_FILE}</string>

  <key>ProcessType</key>
  <string>Background</string>

  <key>KeepAlive</key>
  <true/>
</dict>
</plist>
EOF

#--- load it --------------------------------------------------------------
launchctl bootout "gui/$(id -u)/${LABEL}" 2>/dev/null || true
if launchctl bootstrap "gui/$(id -u)" "$PLIST_PATH" 2>&1 | head -20; then
  log "✅ loaded launchd job: $LABEL"
  log "first sync starts ≤5s"
  log "logs: tail -F $LOG_FILE"
  log "uninstall:"
  log "   bash $0 --uninstall"
else
  err "launchctl bootstrap failed — see $LOG_FILE for hints"
  exit 3
fi

#--- log the install to gbrain audit --------------------------------------
export PATH="$HOME/.bun/bin:$HOME/.local/bin:$PATH"
if command -v gbrain >/dev/null 2>&1; then
  gbrain import "$REPO_PATH/ai_context" \
                 "$REPO_PATH/docs/intake" 2>/dev/null && \
    log "first import of $(hostname) into local gbrain ✓"
fi

exit 0
