#!/bin/bash
# Script to re-apply OmniRoute prefix-strip and alias patches inside the docker container
# Auto-generated by Antigravity (Hermes Agent) - 2026-07-04

set -e

CONTAINER_NAME="omniroute"

echo "=== Starting OmniRoute Post-Update Patching ==="

# Check container running
if [ "$(sudo docker inspect -f '{{.State.Running}}' ${CONTAINER_NAME} 2>/dev/null)" != "true" ]; then
    echo "ERROR: Container ${CONTAINER_NAME} is not running!"
    exit 1
fi

# Run the python patching script inside the host context
sudo python3 -c '
import subprocess

files_executor = ["37544.js", "87107.js"]
old_pattern = '\''if("object"==typeof f&&null!==f){let a=(0,j.qs)(this.provider);if(a?.modelIdPrefix){let b=f;"string"==typeof b.model&&([a.modelIdPrefix,...a.acceptedModelIdPrefixes??[]].some(a=>b.model.startsWith(a))||(b.model=`${a.modelIdPrefix}${b.model}`))}}return f'\''
new_pattern = '\''if("object"==typeof f&&null!==f){let a=(0,j.qs)(this.provider);if(a?.modelIdPrefix){let b=f;"string"==typeof b.model&&([a.modelIdPrefix,...a.acceptedModelIdPrefixes??[]].some(a=>b.model.startsWith(a))||(b.model=`${a.modelIdPrefix}${b.model}`))};this.provider&&"string"==typeof f.model&&f.model.startsWith(this.provider+"/")&&(f.model=f.model.slice(this.provider.length+1))}return f'\''

print("Applying prefix-strip patches...")
for filename in files_executor:
    subprocess.run(["sudo", "docker", "cp", f"omniroute:/app/.build/next/server/chunks/{filename}", f"/tmp/{filename}"])
    with open(f"/tmp/{filename}", "r") as f:
        content = f.read()
    if old_pattern in content:
        # Bach up in container
        subprocess.run(["sudo", "docker", "exec", "-u", "root", "omniroute", "cp", f"/app/.build/next/server/chunks/{filename}", f"/app/.build/next/server/chunks/{filename}.bak"])
        patched = content.replace(old_pattern, new_pattern)
        with open(f"/tmp/{filename}_patched.js", "w") as f:
            f.write(patched)
        subprocess.run(["sudo", "docker", "cp", f"/tmp/{filename}_patched.js", f"omniroute:/app/.build/next/server/chunks/{filename}"])
        print(f"Patched {filename} successfully.")
    elif new_pattern in content:
        print(f"{filename} already patched.")
    else:
        print(f"WARNING: Pattern not found in {filename}!")

files_alias = ["4960.js", "73671.js"]
old_large = '\''"mistral-large":"mistral-large-latest"'\''
new_large = '\''"mistral-large":"mistral-large"'\''
old_small = '\''"mistral-small":"mistral-small-latest"'\''
new_small = '\''"mistral-small":"mistral-small"'\''

print("\nApplying alias mapping patches...")
for filename in files_alias:
    subprocess.run(["sudo", "docker", "cp", f"omniroute:/app/.build/next/server/chunks/{filename}", f"/tmp/{filename}"])
    with open(f"/tmp/{filename}", "r") as f:
        content = f.read()
    if old_large in content or old_small in content:
        subprocess.run(["sudo", "docker", "exec", "-u", "root", "omniroute", "cp", f"/app/.build/next/server/chunks/{filename}", f"/app/.build/next/server/chunks/{filename}.bak"])
        patched = content
        if old_large in patched:
            patched = patched.replace(old_large, new_large)
        if old_small in patched:
            patched = patched.replace(old_small, new_small)
        with open(f"/tmp/{filename}_patched.js", "w") as f:
            f.write(patched)
        subprocess.run(["sudo", "docker", "cp", f"/tmp/{filename}_patched.js", f"omniroute:/app/.build/next/server/chunks/{filename}"])
        print(f"Patched {filename} successfully.")
    elif new_large in content:
        print(f"{filename} already patched.")
    else:
        print(f"WARNING: Targets not found in {filename}!")
'

echo "=== Restarting OmniRoute Container ==="
sudo docker restart ${CONTAINER_NAME}
echo "=== Patches Re-Applied Successfully ==="
