#!/usr/bin/env python3
import subprocess
import sys

EXPANSION_ISSUES = [
    {
        "title": "AI-EXPONENTIAL: Jito MEV Bundle Staking Integration",
        "priority": "priority:P0",
        "body": """### Goal
Guarantee staking transaction execution during network congestion and optimize validator tip routing by integrating with Jito bundles.

### Checklist
- Integrate Jito's JSON-RPC API (`sendBundle` endpoint) in `vault_crank.ts`.
- Implement automatic MEV tip calculation and append tip transfer instructions to staking transaction packages.
"""
    },
    {
        "title": "AI-EXPONENTIAL: Client-Side WASM/WebGPU Match Simulator & Live Commentary Engine",
        "priority": "priority:P1",
        "body": """### Goal
Drive user engagement by simulating matches client-side with rich scrolling text commentary generated by Web Workers and WebGPU.

### Checklist
- Build a Web Worker-based match simulator in `goalworld_webapp/src/` that runs off-main-thread.
- Implement a lightweight local parser using WASM or WebGPU to generate real-time, stylized soccer commentary based on player statistics.
"""
    },
    {
        "title": "AI-EXPONENTIAL: Premium Glassmorphic Staking & Infinity Burn Dashboard",
        "priority": "priority:P0",
        "body": """### Goal
Provide a high-fidelity visual experience representing $GCH burns and staking yields with responsive glassmorphism.

### Checklist
- Revamp the React staking UI with hardware-accelerated SVG flame animations, glassmorphic cards, and interactive yield calculators.
- Implement real-time stats mapping from the Express API economy endpoints.
"""
    },
    {
        "title": "AI-EXPONENTIAL: Consensus-Driven Multi-Source Oracle Scraper",
        "priority": "priority:P1",
        "body": """### Goal
Remove single points of failure in sports score ingestion by scraping ESPN and SofaScore in parallel.

### Checklist
- Refactor `oracle_scraper.py` to fetch live soccer scores from multiple providers (e.g. ESPN, SofaScore, Transfermarkt) in parallel.
- Implement a simple consensus algorithm to resolve discrepancies before writing the canonical match state.
"""
    },
    {
        "title": "AI-EXPONENTIAL: OpenTelemetry & Prometheus Ingestion Metrics",
        "priority": "priority:P2",
        "body": """### Goal
Track system health and burn metrics for presale campaigns.

### Checklist
- Integrate `prom-client` or OpenTelemetry in the Express API to expose real-time metrics (RPC health, burn rate, Presale SOL totals).
- Expose a `/metrics` scrape endpoint for Prometheus dashboard visualization.
"""
    },
    {
        "title": "AI-AUDIT: Resilient Vault Crank Jupiter Swaps",
        "priority": "priority:P0",
        "body": """### Goal
Replace the risky SOL transfer fallback in `vault_crank.ts` with Jupiter swap token burns, verify the returned transaction, and handle token-burning.

### Checklist
- Locate `vault_crank.ts` mainnet execution path.
- Replace the `SystemProgram.transfer` fallback with a proper checked Jupiter swap instruction or raise a validated error.
- Add transaction preflight simulation (`simulateTransaction`) before transaction submission.
- Ensure Jupiter swap logic works with Versioned Transactions and handles token-burning correctly.
"""
    },
    {
        "title": "AI-AUDIT: Minimum Priority Fee Floors & Compute Unit Caching",
        "priority": "priority:P1",
        "body": """### Goal
Enforce minimum priority fee floors via environment variables and cache compute unit estimates in `priorityFees.ts`.

### Checklist
- Add support for loading `PRIORITY_FEE_FLOOR` from environment variables.
- Cache compute unit estimates with a TTL (5-15 seconds) inside `priorityFees.ts` to reduce RPC pressure.
"""
    },
    {
        "title": "AI-AUDIT: Add Transaction Simulation (simulateTransaction) to Critical Paths",
        "priority": "priority:P1",
        "body": """### Goal
Run transaction simulations before every mainnet submission to catch failures pre-flight.

### Checklist
- Implement `simulateTransaction` calls before submitting any on-chain transaction in `vault_crank.ts` and Oracle paths.
- Log simulation details and halt execution if the simulation fails.
"""
    },
    {
        "title": "AI-AUDIT: Standardize Logging with Winston/Pino across API & Oracle",
        "priority": "priority:P2",
        "body": """### Goal
Replace generic `console.log` statements with structured, JSON-formatted logs using winston or pino for better cloud monitoring.

### Checklist
- Integrate `pino` or `winston` in both the Express API and Oracle daemon.
- Format logs as JSON for integration with cloud logging services.
"""
    },
    {
        "title": "AI-AUDIT: Document All Environment Variables in .env.example",
        "priority": "priority:P2",
        "body": """### Goal
Create a complete `.env.example` file detailing all configuration requirements, defaults, and security notices.

### Checklist
- Audit all environment variable usage in `goalworld_api`, `goalworld_oracle`, and scripts.
- Document all environment variables in `.env.example` with descriptions, defaults, and security notices.
"""
    },
    {
        "title": "AI-AUDIT: Fix computeMintGateFromRows & WSOL Fallbacks",
        "priority": "priority:P1",
        "body": """### Goal
Fix edge cases in `computeMintGateFromRows` (empty selections) and remove dangerous fallback mint resolutions to WSOL in `vault_crank.ts:217`.

### Checklist
- Ensure `computeMintGateFromRows` handles empty selected arrays gracefully.
- Remove dangerous fallback mint resolution to WSOL in `vault_crank.ts:217`.
"""
    }
]

def create_issue(issue):
    cmd = [
        "gh", "issue", "create",
        "--title", issue["title"],
        "--body", issue["body"],
        "--label", "status:ready",
        "--label", "agent:opencode",
        "--label", issue["priority"]
    ]
    print(f"Creating issue: {issue['title']}...")
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode == 0:
        issue_url = res.stdout.strip()
        issue_num = issue_url.split("/")[-1]
        print(f"Successfully created Issue #{issue_num}: {issue_url}")
        return issue_num
    else:
        print(f"Failed to create issue: {res.stderr}")
        return None

def main():
    created = []
    for issue in EXPANSION_ISSUES:
        num = create_issue(issue)
        if num:
            created.append(num)
    
    print(f"\nDone! Created {len(created)} issues: {', '.join(created)}")

if __name__ == "__main__":
    main()
