from __future__ import annotations

import re
from goalworld_multiagent.config import get_settings
from goalworld_multiagent.github_api import create_github_issue
from goalworld_multiagent.slack_api import notify_agent_step_slack
from goalworld_multiagent.state import GraphState


def dev_node(state: GraphState) -> GraphState:
    objective = (state.get("objective") or "").strip()
    trace = list(state.get("route_trace") or [])
    trace.append("dev")

    body = f"""## Objective
{objective}

## Context
Generated by goalworld LangGraph Dev agent (Fase 2). Do not merge without Antigravity review.

## Allowed files
TBD — scope in intake brief.

## Out of scope
On-chain mainnet, treasury, mint gates, `ECONOMIC_CANONICAL_CONFIG.json` value changes.

## Acceptance criteria
- [ ] Tests listed in issue body pass
- [ ] Draft PR only (`exp/opencode-issue-*`)

## Owner
agent:opencode (FCC)

## Test commands
`cd goalworld_webapp && npm run build` (if webapp touched)
"""

    settings = get_settings()
    title = f"[LangGraph] {objective[:72]}"
    repo = settings.github_repo or "TheNeuralWars/goalworld"

    # Trigger real issue creation if write enabled and intent is explicit
    write_enabled = settings.goalworld_ma_dev_write_github
    wants_create = bool(re.search(r"\b(crear|create|dispatch|generate|generar)\s+issue\b", objective.lower()))

    issue_info = None
    msg = "Prepared GitHub issue draft; execution via FCC, not direct repo write."

    if write_enabled and wants_create:
        issue_info = create_github_issue(
            title=title,
            body=body,
            repo=repo,
            labels=["agent:opencode", "status:ready"],
        )
        if issue_info:
            msg = f"Actively created GitHub issue #{issue_info['number']} on repo {repo}."
            
            # Push elegant slack notification for our internal logs pipeline
            if settings.goalworld_ma_slack_webhook.strip():
                try:
                    notify_agent_step_slack(
                        agent_name="dev",
                        objective=objective,
                        content=msg,
                        meta={
                            "Issue Number": str(issue_info["number"]),
                            "GitHub Link": issue_info["url"],
                        },
                        settings=settings,
                    )
                except Exception:  # noqa: BLE001
                    pass
        else:

            msg = "Attempted to create GitHub issue, but the subprocess execution failed."

    artifacts = list(state.get("artifacts") or [])
    if issue_info:
        artifacts.append(
            {
                "type": "github_issue",
                "title": title,
                "body": body,
                "meta": {
                    "number": issue_info["number"],
                    "url": issue_info["url"],
                    "repo": repo,
                    "live": True,
                },
            }
        )
    else:
        artifacts.append(
            {
                "type": "github_issue_draft",
                "title": title,
                "body": body,
                "meta": {
                    "suggested_label": "agent:opencode",
                    "live": False,
                },
            }
        )

    return {
        "route_trace": trace,
        "artifacts": artifacts,
        "messages": (state.get("messages") or [])
        + [
            {
                "role": "dev",
                "content": msg,
            }
        ],
        "next_agent": "ceo",
    }

